### PR TITLE
Add binary extensions

### PR DESCRIPTION
**Pull request by Marko10-000**

### CODE REVIEW

**Comment by comparascope** [comment]
Why does this need cmake as a submodule?

**Comment by comparascope** [comment]
if we could download and extract files before building and not need download during build, we should try that

**Comment by Marko10-000** [comment]
Cmake is required, because the delivered Cmake has a bug (it can't use https). As long as we download packages during the build the recompiled Cmake is required. When we could achieve to get a offline package, etc. for the binary addons an own compiled cmake isn't required.

**Comment by Marko10-000** [comment]
A better solution already exists.

**Pull request closed without merging**
